// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.weibo.wejoy.data.model;

public final class MessageWrap {
  private MessageWrap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 msgid = 101;
    boolean hasMsgid();
    long getMsgid();
    
    // required uint64 fromuid = 102;
    boolean hasFromuid();
    long getFromuid();
    
    // required uint64 touid = 103;
    boolean hasTouid();
    long getTouid();
    
    // required uint32 type = 104;
    boolean hasType();
    int getType();
    
    // required string content = 105;
    boolean hasContent();
    String getContent();
    
    // required uint64 ctime = 106;
    boolean hasCtime();
    long getCtime();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weibo.wejoy.data.model.MessageWrap.internal_static_weibo_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weibo.wejoy.data.model.MessageWrap.internal_static_weibo_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 msgid = 101;
    public static final int MSGID_FIELD_NUMBER = 101;
    private long msgid_;
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getMsgid() {
      return msgid_;
    }
    
    // required uint64 fromuid = 102;
    public static final int FROMUID_FIELD_NUMBER = 102;
    private long fromuid_;
    public boolean hasFromuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getFromuid() {
      return fromuid_;
    }
    
    // required uint64 touid = 103;
    public static final int TOUID_FIELD_NUMBER = 103;
    private long touid_;
    public boolean hasTouid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getTouid() {
      return touid_;
    }
    
    // required uint32 type = 104;
    public static final int TYPE_FIELD_NUMBER = 104;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getType() {
      return type_;
    }
    
    // required string content = 105;
    public static final int CONTENT_FIELD_NUMBER = 105;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint64 ctime = 106;
    public static final int CTIME_FIELD_NUMBER = 106;
    private long ctime_;
    public boolean hasCtime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getCtime() {
      return ctime_;
    }
    
    private void initFields() {
      msgid_ = 0L;
      fromuid_ = 0L;
      touid_ = 0L;
      type_ = 0;
      content_ = "";
      ctime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTouid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(101, msgid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(102, fromuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(103, touid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(104, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(105, getContentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(106, ctime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(101, msgid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(102, fromuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(103, touid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(104, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(105, getContentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(106, ctime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MessageWrap.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.weibo.wejoy.data.model.MessageWrap.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.weibo.wejoy.data.model.MessageWrap.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.weibo.wejoy.data.model.MessageWrap.internal_static_weibo_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.weibo.wejoy.data.model.MessageWrap.internal_static_weibo_Message_fieldAccessorTable;
      }
      
      // Construct using com.weibo.wesync.data.model.MessageWrap.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromuid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        touid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        ctime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.weibo.wejoy.data.model.MessageWrap.Message.getDescriptor();
      }
      
      public com.weibo.wejoy.data.model.MessageWrap.Message getDefaultInstanceForType() {
        return com.weibo.wejoy.data.model.MessageWrap.Message.getDefaultInstance();
      }
      
      public com.weibo.wejoy.data.model.MessageWrap.Message build() {
        com.weibo.wejoy.data.model.MessageWrap.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.weibo.wejoy.data.model.MessageWrap.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.weibo.wejoy.data.model.MessageWrap.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.weibo.wejoy.data.model.MessageWrap.Message buildPartial() {
        com.weibo.wejoy.data.model.MessageWrap.Message result = new com.weibo.wejoy.data.model.MessageWrap.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgid_ = msgid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromuid_ = fromuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.touid_ = touid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ctime_ = ctime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.weibo.wejoy.data.model.MessageWrap.Message) {
          return mergeFrom((com.weibo.wejoy.data.model.MessageWrap.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.weibo.wejoy.data.model.MessageWrap.Message other) {
        if (other == com.weibo.wejoy.data.model.MessageWrap.Message.getDefaultInstance()) return this;
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        if (other.hasFromuid()) {
          setFromuid(other.getFromuid());
        }
        if (other.hasTouid()) {
          setTouid(other.getTouid());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasCtime()) {
          setCtime(other.getCtime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgid()) {
          
          return false;
        }
        if (!hasFromuid()) {
          
          return false;
        }
        if (!hasTouid()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!hasCtime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 808: {
              bitField0_ |= 0x00000001;
              msgid_ = input.readUInt64();
              break;
            }
            case 816: {
              bitField0_ |= 0x00000002;
              fromuid_ = input.readUInt64();
              break;
            }
            case 824: {
              bitField0_ |= 0x00000004;
              touid_ = input.readUInt64();
              break;
            }
            case 832: {
              bitField0_ |= 0x00000008;
              type_ = input.readUInt32();
              break;
            }
            case 842: {
              bitField0_ |= 0x00000010;
              content_ = input.readBytes();
              break;
            }
            case 848: {
              bitField0_ |= 0x00000020;
              ctime_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 msgid = 101;
      private long msgid_ ;
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getMsgid() {
        return msgid_;
      }
      public Builder setMsgid(long value) {
        bitField0_ |= 0x00000001;
        msgid_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgid_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint64 fromuid = 102;
      private long fromuid_ ;
      public boolean hasFromuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getFromuid() {
        return fromuid_;
      }
      public Builder setFromuid(long value) {
        bitField0_ |= 0x00000002;
        fromuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearFromuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromuid_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint64 touid = 103;
      private long touid_ ;
      public boolean hasTouid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTouid() {
        return touid_;
      }
      public Builder setTouid(long value) {
        bitField0_ |= 0x00000004;
        touid_ = value;
        onChanged();
        return this;
      }
      public Builder clearTouid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        touid_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint32 type = 104;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required string content = 105;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
      }
      
      // required uint64 ctime = 106;
      private long ctime_ ;
      public boolean hasCtime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getCtime() {
        return ctime_;
      }
      public Builder setCtime(long value) {
        bitField0_ |= 0x00000020;
        ctime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCtime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ctime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:weibo.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:weibo.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_weibo_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_weibo_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\005weibo\"f\n\007Message\022\r\n\005msg" +
      "id\030e \002(\004\022\017\n\007fromuid\030f \002(\004\022\r\n\005touid\030g \002(\004" +
      "\022\014\n\004type\030h \002(\r\022\017\n\007content\030i \002(\t\022\r\n\005ctime" +
      "\030j \002(\004B*\n\033com.weibo.wesync.data.modelB\013M" +
      "essageWrap"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_weibo_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_weibo_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_weibo_Message_descriptor,
              new java.lang.String[] { "Msgid", "Fromuid", "Touid", "Type", "Content", "Ctime", },
              com.weibo.wejoy.data.model.MessageWrap.Message.class,
              com.weibo.wejoy.data.model.MessageWrap.Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
