// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta_message_pb.proto

package com.weibo.wejoy.data.model;

public final class MetaMessagePBWrap {
  private MetaMessagePBWrap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetaMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 101;
    boolean hasId();
    String getId();
    
    // required bytes meta = 102;
    boolean hasMeta();
    com.google.protobuf.ByteString getMeta();
    
    // required string type = 103;
    boolean hasType();
    String getType();
  }
  public static final class MetaMessage extends
      com.google.protobuf.GeneratedMessage
      implements MetaMessageOrBuilder {
    // Use MetaMessage.newBuilder() to construct.
    private MetaMessage(Builder builder) {
      super(builder);
    }
    private MetaMessage(boolean noInit) {}
    
    private static final MetaMessage defaultInstance;
    public static MetaMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public MetaMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weibo.wejoy.data.model.MetaMessagePBWrap.internal_static_weibo_MetaMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weibo.wejoy.data.model.MetaMessagePBWrap.internal_static_weibo_MetaMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 101;
    public static final int ID_FIELD_NUMBER = 101;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes meta = 102;
    public static final int META_FIELD_NUMBER = 102;
    private com.google.protobuf.ByteString meta_;
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getMeta() {
      return meta_;
    }
    
    // required string type = 103;
    public static final int TYPE_FIELD_NUMBER = 103;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      meta_ = com.google.protobuf.ByteString.EMPTY;
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMeta()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(101, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(102, meta_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(103, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(101, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(102, meta_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(103, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.weibo.wejoy.data.model.MetaMessagePBWrap.internal_static_weibo_MetaMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.weibo.wejoy.data.model.MetaMessagePBWrap.internal_static_weibo_MetaMessage_fieldAccessorTable;
      }
      
      // Construct using com.weibo.wesync.data.model.MetaMessagePBWrap.MetaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        meta_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage.getDescriptor();
      }
      
      public com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage getDefaultInstanceForType() {
        return com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage.getDefaultInstance();
      }
      
      public com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage build() {
        com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage buildPartial() {
        com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage result = new com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.meta_ = meta_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage) {
          return mergeFrom((com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage other) {
        if (other == com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMeta()) {
          setMeta(other.getMeta());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasMeta()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 810: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 818: {
              bitField0_ |= 0x00000002;
              meta_ = input.readBytes();
              break;
            }
            case 826: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 101;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required bytes meta = 102;
      private com.google.protobuf.ByteString meta_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMeta() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getMeta() {
        return meta_;
      }
      public Builder setMeta(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        meta_ = value;
        onChanged();
        return this;
      }
      public Builder clearMeta() {
        bitField0_ = (bitField0_ & ~0x00000002);
        meta_ = getDefaultInstance().getMeta();
        onChanged();
        return this;
      }
      
      // required string type = 103;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:weibo.MetaMessage)
    }
    
    static {
      defaultInstance = new MetaMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:weibo.MetaMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_weibo_MetaMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_weibo_MetaMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025meta_message_pb.proto\022\005weibo\"5\n\013MetaMe" +
      "ssage\022\n\n\002id\030e \002(\t\022\014\n\004meta\030f \002(\014\022\014\n\004type\030" +
      "g \002(\tB0\n\033com.weibo.wesync.data.modelB\021Me" +
      "taMessagePBWrap"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_weibo_MetaMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_weibo_MetaMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_weibo_MetaMessage_descriptor,
              new java.lang.String[] { "Id", "Meta", "Type", },
              com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage.class,
              com.weibo.wejoy.data.model.MetaMessagePBWrap.MetaMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
